// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtTvRisE3g6W8Ck5PDVUKEUQ_WoG7G0jA',
    appId: '1:453871935398:web:1d42a42771c4d56f13f967',
    messagingSenderId: '453871935398',
    projectId: 'user-auth-money-track',
    authDomain: 'user-auth-money-track.firebaseapp.com',
    storageBucket: 'user-auth-money-track.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZfB1H0D8oejlP5L5OgtuoVG_aK6ffLg',
    appId: '1:453871935398:android:289254649b884eed13f967',
    messagingSenderId: '453871935398',
    projectId: 'user-auth-money-track',
    storageBucket: 'user-auth-money-track.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCM0A_xt8llJQkCuOQZke8CGnon17Va90',
    appId: '1:453871935398:ios:2b0e41a8df7bbe6913f967',
    messagingSenderId: '453871935398',
    projectId: 'user-auth-money-track',
    storageBucket: 'user-auth-money-track.appspot.com',
    iosClientId: '453871935398-uv664clns33dtraqjf04g91o3hoasefi.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCM0A_xt8llJQkCuOQZke8CGnon17Va90',
    appId: '1:453871935398:ios:71bca7a7517619cf13f967',
    messagingSenderId: '453871935398',
    projectId: 'user-auth-money-track',
    storageBucket: 'user-auth-money-track.appspot.com',
    iosClientId: '453871935398-6jslhgeg52lhoq0gq21pjpqlp50a13ie.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyTrack.RunnerTests',
  );
}
